# Generated by Django 3.2.4 on 2021-07-04 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210703_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 13, 40, 36, 621756, tzinfo=utc)),
        ),
    ]
