# Generated by Django 3.2.4 on 2021-07-04 20:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_new_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 20, 39, 50, 841098, tzinfo=utc)),
        ),
    ]
