# Generated by Django 3.2.4 on 2021-07-06 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_new_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 17, 49, 6, 392409, tzinfo=utc)),
        ),
    ]
